In [3]:
import os
os.getcwd()
os.chdir('C:\\Users\\meric\Desktop\codes')

In [4]:
import pandas as pd
df=pd.read_csv('Advertising.csv')
# df=df.iloc[:,1:len(df)]
df.head()
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  200 non-null    int64  
 1   TV          200 non-null    float64
 2   Radio       200 non-null    float64
 3   Newspaper   200 non-null    float64
 4   Sales       200 non-null    float64
dtypes: float64(4), int64(1)
memory usage: 7.9 KB


In [5]:
from sklearn.linear_model import LinearRegression
X=df[["TV","Radio","Newspaper"]]
# X.head()
Y=df[["Sales"]]
# Y.head()

In [6]:
import statsmodels.api as sm

lm=sm.OLS(Y,X)
model=lm.fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  Sales   R-squared (uncentered):                   0.982
Model:                            OLS   Adj. R-squared (uncentered):              0.982
Method:                 Least Squares   F-statistic:                              3566.
Date:                Sun, 17 Jan 2021   Prob (F-statistic):                   2.43e-171
Time:                        02:24:05   Log-Likelihood:                         -423.54
No. Observations:                 200   AIC:                                      853.1
Df Residuals:                     197   BIC:                                      863.0
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0538      0.001     40.507      0.000       0.051       0.056
Radio          0.2222      0.009     23.595      0.000       0.204       0.241
Newspaper      0.0168      0.007      2.517      0.013       0.004       0.030
==============================================================================
Omnibus:                        5.982   Durbin-Watson:                   2.038
Prob(Omnibus):                  0.050   Jarque-Bera (JB):                7.039
Skew:                          -0.232   Prob(JB):                       0.0296
Kurtosis:                       3.794   Cond. No.                         12.6
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [7]:
from sklearn.linear_model import LinearRegression
##scikit learn ile model kurmak
lm=LinearRegression()
model=lm.fit(X,Y)
model.intercept_
model.coef_

array([[ 0.04576465,  0.18853002, -0.00103749]])

In [8]:
yeni_veri=[[30],[10],[40]]
yeni_veri=pd.DataFrame(yeni_veri).T
yeni_veri

0   1   2
0  30  10  40

In [9]:
model.predict(yeni_veri)

array([[6.15562918]])

In [10]:
from sklearn.metrics import mean_squared_error
# MSE
MSE=mean_squared_error(Y,model.predict(X))

In [11]:
import numpy as np
RMSE=np.sqrt(MSE)
RMSE

1.6685701407225697

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.20,random_state=99)
x_train
y_train
x_test
y_test.describe()


Sales
count  40.000000
mean   13.070000
std     5.127513
min     3.200000
25%     9.650000
50%    11.800000
75%    16.625000
max    25.400000

In [24]:
# egitim hatası
lm=LinearRegression()
model=lm.fit(x_train,y_train)
np.sqrt(mean_squared_error(y_train,model.predict(x_train)))

1.7236824822650751

In [34]:
# test hatası
np.sqrt(mean_squared_error(y_test,model.predict(x_test)))

1.4312783138301641

In [35]:
# cvint, cross-validation generator or an iterable, default=None
from sklearn.model_selection import cross_val_score
cross_val_score(model,x_train,y_train,cv=10,scoring="neg_mean_squared_error")

array([-2.1019073 , -2.48953197, -3.09704214, -2.34694216, -3.68175761,
       -1.8691401 , -3.18173007, -4.1927349 , -2.17128376, -8.03821974])

In [36]:
np.mean(-cross_val_score(model,x_train,y_train,cv=10,scoring="neg_mean_squared_error"))

3.3170289742341255